DRIVING_LIMIT_HOURS = 11
DUTY_WINDOW_HOURS = 14
BREAK_REQUIRED_AFTER_HOURS = 8
BREAK_DURATION_HOURS = 0.5
OFF_DUTY_RESET_HOURS = 10
CYCLE_LIMIT_HOURS = 70
CYCLE_WINDOW_DAYS = 8

PICKUP_DURATION_HOURS = 1
DROPOFF_DURATION_HOURS = 1

FUEL_INTERVAL_MILES = 1000
FUEL_DURATION_HOURS = 0.5  #This is an assumption for refuling time as it's not mentioned (refuling atleast once after every 1000 miles it takes 30 min)

RESTART_HOURS = 34